services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - target
    environment:
      - PORT=3000
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"